/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.member;

import controler.Controler;
import domain.Member;
import form.FrmMode;
import form.MainForm;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import transfer.Response;
import validator.FormValidator;

/**
 *
 * @author Monika
 */
public class MemberForm extends javax.swing.JDialog {
    Border border;
    MainForm mf;
    ViewMemberForm vmf;
    Member m;

    /**
     * Creates new form MemberForm
     */
   
    public MemberForm(MainForm parent, boolean modal, FrmMode frmMode) {
        super(parent,modal);
        mf = parent;
        initComponents();
        setScreenCenter();
        adjustForm(frmMode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMember = new javax.swing.JPanel();
        txtLastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtScore = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Email:");

        jLabel6.setText("Total score:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel3.setText("First name:");

        jLabel4.setText("Last name:");

        javax.swing.GroupLayout panelMemberLayout = new javax.swing.GroupLayout(panelMember);
        panelMember.setLayout(panelMemberLayout);
        panelMemberLayout.setHorizontalGroup(
            panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMemberLayout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMemberLayout.createSequentialGroup()
                        .addGroup(panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFirstname)
                            .addComponent(txtLastname)
                            .addComponent(txtEmail)
                            .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelMemberLayout.setVerticalGroup(
            panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMemberLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnSave))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    
        if(!validation())
            return;
        
        String firstname = txtFirstname.getText();
        String lastname = txtLastname.getText();
        String email = txtEmail.getText();
        int score = Integer.parseInt(txtScore.getText());
        
        Member m = new Member(-1, firstname, lastname, email, score);

        Response res = Controler.getInstance().save(m);

        if (res.isStatus()) {
            JOptionPane.showMessageDialog(this, res.getMessage(), "Successful", JOptionPane.INFORMATION_MESSAGE);
            resetForm();
            mf.setPanel(new ViewMemberForm(mf));
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(this, res.getMessage(), "Unsuccessful", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        if(!validation())
            return;
        String firstname = txtFirstname.getText();
        String lastname = txtLastname.getText();
        String email = txtEmail.getText();
        int score = Integer.parseInt(txtScore.getText());
        
        m.setFirstname(firstname);
        m.setLastname(lastname);
        m.setEmail(email);
        m.setTotalScore(score);
        Response res = Controler.getInstance().update(m);

        if (res.isStatus()) {
            JOptionPane.showMessageDialog(this, res.getMessage(), "Successful", JOptionPane.INFORMATION_MESSAGE);
            resetForm();
           
            vmf.populateTable();
            vmf.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, res.getMessage(), "Unsuccessful", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelMember;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtScore;
    // End of variables declaration//GEN-END:variables

    private void resetForm() {
        txtFirstname.setText("");
        txtLastname.setText("");
        txtEmail.setText("");
        txtScore.setText("");
    }

    private void adjustForm(FrmMode mode) {
    
        switch (mode) {
            case NEW:
                String title = "Add member:";
                border = BorderFactory.createTitledBorder(title);
                panelMember.setBorder(border);
                btnSave.setVisible(true);
                btnEdit.setVisible(false);                
                break;
            case EDIT:                
                btnSave.setVisible(false);
                btnEdit.setVisible(true);
                title = "Edit member:";
                border = BorderFactory.createTitledBorder(title);
                panelMember.setBorder(border);
                break;
            
        }
    }
    
     void populateEditForm(Member m, ViewMemberForm vmf) {
        adjustForm(FrmMode.EDIT);
        this.m = m;
        this.vmf = vmf;
        txtFirstname.setText(m.getFirstname());
        txtLastname.setText(m.getLastname());
        txtEmail.setText(m.getEmail());
        txtScore.setText(m.getTotalScore()+"");
    }

    private boolean validation() {
        if (!FormValidator.getInstance().validateEmpty(txtFirstname, txtLastname, txtEmail, txtScore)) {
            JOptionPane.showMessageDialog(panelMember, FormValidator.getInstance().getValidationMessage(), "Error",JOptionPane.ERROR_MESSAGE );
            return false;
        }

        String firstname = txtFirstname.getText();
        String lastname = txtLastname.getText();
        String email = txtEmail.getText();
        int score = 0;

         try {
            score = Integer.parseInt(txtScore.getText());
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Score needs to be numeric value!");
            return false;
        }
         
        if(!txtEmail.getText().contains("@") || txtEmail.getText().endsWith("@") || 
                txtEmail.getText().startsWith("@") || txtEmail.getText().contains(" ") ){
            JOptionPane.showMessageDialog(this, "Email format is not valid!");
            return false;
        }
        return true;
    }
    
    private void setScreenCenter() {
        setLocationRelativeTo(null);      
    }
}
