/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controler.Controler;
import domain.User;
import form.member.MemberForm;
import form.member.ViewMemberForm;
import form.projection.ProjectionForm;
import form.projection.ViewProjectionForm;
import form.reservation.ReservationForm;
import form.reservation.ViewReservationForm;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Monika
 */
public class MainForm extends javax.swing.JFrame {

    private ReservationForm rf;
    private ProjectionForm pf;
    private MemberForm mf;
    private ViewReservationForm vrf;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setScreenCenter();
        populatePanelCurrentUser();
        Controler.getInstance().setMf(this);
    }

    public JPanel getPanel() {
        return panel;
    }

    public MemberForm getMf() {
        return mf;
    }

    public ProjectionForm getPf() {
        return pf;
    }

    public ReservationForm getRf() {
        return rf;
    }

    public ViewReservationForm getVrf() {
        return vrf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        panelCurrentUser = new javax.swing.JPanel();
        labelCurrentUser = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmMember = new javax.swing.JMenu();
        jmiNewMember = new javax.swing.JMenuItem();
        jmiViewMembers = new javax.swing.JMenuItem();
        jmReservation = new javax.swing.JMenu();
        jmiNewReservation = new javax.swing.JMenuItem();
        jmiViewReservation = new javax.swing.JMenuItem();
        jmProjection = new javax.swing.JMenu();
        jmiNewProjection = new javax.swing.JMenuItem();
        jmiViewProjection = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cinema");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelCurrentUser.setBorder(javax.swing.BorderFactory.createTitledBorder("User:"));

        labelCurrentUser.setText("Current user:");

        javax.swing.GroupLayout panelCurrentUserLayout = new javax.swing.GroupLayout(panelCurrentUser);
        panelCurrentUser.setLayout(panelCurrentUserLayout);
        panelCurrentUserLayout.setHorizontalGroup(
            panelCurrentUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurrentUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCurrentUser)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        panelCurrentUserLayout.setVerticalGroup(
            panelCurrentUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurrentUserLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelCurrentUser)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        panelMain.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );

        jmMember.setText("Member");

        jmiNewMember.setText("New member");
        jmiNewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewMemberActionPerformed(evt);
            }
        });
        jmMember.add(jmiNewMember);

        jmiViewMembers.setText("View members");
        jmiViewMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewMembersActionPerformed(evt);
            }
        });
        jmMember.add(jmiViewMembers);

        jMenuBar2.add(jmMember);

        jmReservation.setText("Reservation");

        jmiNewReservation.setText("New reservation");
        jmiNewReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewReservationActionPerformed(evt);
            }
        });
        jmReservation.add(jmiNewReservation);

        jmiViewReservation.setText("View reservations");
        jmiViewReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewReservationActionPerformed(evt);
            }
        });
        jmReservation.add(jmiViewReservation);

        jMenuBar2.add(jmReservation);

        jmProjection.setText("Projection");

        jmiNewProjection.setText("New projection");
        jmiNewProjection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewProjectionActionPerformed(evt);
            }
        });
        jmProjection.add(jmiNewProjection);

        jmiViewProjection.setText("View projections");
        jmiViewProjection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewProjectionActionPerformed(evt);
            }
        });
        jmProjection.add(jmiViewProjection);

        jMenuBar2.add(jmProjection);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCurrentUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNewReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewReservationActionPerformed
        rf = new ReservationForm(this, true, FrmMode.NEW);
        rf.setVisible(true);
    }//GEN-LAST:event_jmiNewReservationActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        String message = Controler.getInstance().end();
        JOptionPane.showMessageDialog(this, message, "Goodbye!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_formWindowClosing

    private void jmiViewReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewReservationActionPerformed
        vrf = new ViewReservationForm(this);
        panel = vrf;
        setPanel(panel);
    }//GEN-LAST:event_jmiViewReservationActionPerformed

    private void jmiNewProjectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewProjectionActionPerformed
        pf = new ProjectionForm(this, true, FrmMode.NEW);
        pf.setVisible(true);
    }//GEN-LAST:event_jmiNewProjectionActionPerformed

    private void jmiViewProjectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewProjectionActionPerformed
        panel = new ViewProjectionForm(this);
        setPanel(panel);
    }//GEN-LAST:event_jmiViewProjectionActionPerformed

    private void jmiNewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewMemberActionPerformed
        mf = new MemberForm(this, true, FrmMode.NEW);
        mf.setVisible(true);
    }//GEN-LAST:event_jmiNewMemberActionPerformed

    private void jmiViewMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewMembersActionPerformed
        panel = new ViewMemberForm(this);
        setPanel(panel);
    }//GEN-LAST:event_jmiViewMembersActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu jmMember;
    private javax.swing.JMenu jmProjection;
    private javax.swing.JMenu jmReservation;
    private javax.swing.JMenuItem jmiNewMember;
    private javax.swing.JMenuItem jmiNewProjection;
    private javax.swing.JMenuItem jmiNewReservation;
    private javax.swing.JMenuItem jmiViewMembers;
    private javax.swing.JMenuItem jmiViewProjection;
    private javax.swing.JMenuItem jmiViewReservation;
    private javax.swing.JLabel labelCurrentUser;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelCurrentUser;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables

    private void setScreenCenter() {
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void populatePanelCurrentUser() {
        User user = Controler.getInstance().getCurrentUser();
        labelCurrentUser.setText("Current user: " + user.toString());
    }

    public void setPanel(JPanel panel) {
        panelMain.removeAll();
        panelMain.revalidate();

        panelMain.add(panel);
        panelMain.revalidate();
    }
}
